language: node_js
node_js:
  - lts/*
install:
  - cd ./SVG/react-svg-demo/demo
  - yarn install
script:
  - yarn build
  # - cd ./build
  # - git init
  # - git add -A
  # - git commit -m 'deploy'
  # - git push -f git@github.com:YangsonHung/learn-web-development.git master:gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  strategy: git
  local_dir: SVG/react-svg-demo/demo/build
  token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep_history: true
  on:
    branch: master