language: node_js
node_js:
  - lts/*
install:
  - ./deploy.sh
script:
  - ./build.sh
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: SVG/react-svg-demo/demo/build
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master