language: node_js
sudo: required
node_js:
  - lts/*
install:
  - ./deploy.sh
script:
  - ./build.sh
deploy:
  provider: pages
  cleanup: true
  local_dir: SVG/react-svg-demo/demo/build
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master