language: node_js
sudo: required
node_js:
  - lts/*
install:
  - sudo cd ./SVG/react-svg-demo/demo
  - sudo yarn install
script:
  - sudo cd ./SVG/react-svg-demo/demo
  - sudo yarn build
deploy:
  provider: pages
  cleanup: true
  local_dir: SVG/react-svg-demo/demo/build
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master